name: ci

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node: [ 14 ]

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      - name: Setup node env 🏗
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node }}

      - name: Cache node_modules 📦
        uses: actions/cache@v2.1.4
        with:
          path: ~/.npm
          key: ${{ matrix.os }}-node-${{ matrix.node }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ matrix.os }}-node-${{ matrix.node }}-
            ${{ matrix.os }}-node-
            ${{ matrix.os }}-

      - name: Install dependencies 👨🏻‍💻
        run: npm ci

      - name: Run auditer 🚓
        run: npm audit

      - name: Run linter 👀
        run: npm run lint

      - name: Run tests 🧪
        run: npm run test
